
logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.SQL: DEBUG
spring:
  jpa:
    properties:
      hibernate.use_sql_comments: true
      hibernate.jdbc.batch-size: 5
    hibernate:
      ddl-auto: validate
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/{vendor}/common
      - classpath:db/migration/{vendor}/member
      - classpath:db/migration/{vendor}/account
      - classpath:db/migration/{vendor}/transaction
    baseline-version: 1.0
